### PR TITLE
add UESTC and fix ACdream

### PR DESCRIPTION
**Pull request by crccw**
[Review on Reviewable](https://reviewable.io/reviews/bnuacm/bnuoj-vjudge/10)

### CODE REVIEW

**Comment by 51isoft** [comment]
Reviewed files:
- vjudge-v2/ACdreamJudger.cpp @ r1
- vjudge-v2/GlobalHelpers.cpp @ r1
- vjudge-v2/GlobalHelpers.h @ r1
- vjudge-v2/JudgerFactory.cpp @ r1
- vjudge-v2/JudgerFactory.h @ r1
- vjudge-v2/UESTCJudger.cpp @ r1
- vjudge-v2/UESTCJudger.h @ r1

---

<sup>**[vjudge-v2/GlobalHelpers.cpp, line 230 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb7aOoEZT5Mfb9w8ho)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/GlobalHelpers.cpp#L230)):</sup>
space

---

<sup>**[vjudge-v2/GlobalHelpers.cpp, line 232 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb7ZCg5rx-Yi7ghkaN)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/GlobalHelpers.cpp#L232)):</sup>
expand lines

---

<sup>**[vjudge-v2/GlobalHelpers.cpp, line 235 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb7biOfbiexKnFZlVB)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/GlobalHelpers.cpp#L235)):</sup>
case '\n'?

---

<sup>**[vjudge-v2/GlobalHelpers.cpp, line 351 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb6BEfWc6T8Rr8A1gB)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/GlobalHelpers.cpp#L351)):</sup>
spaces

---

<sup>**[vjudge-v2/GlobalHelpers.h, line 44 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb6G_kBIFhYR7o1Ag4)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/GlobalHelpers.h#L44)):</sup>
sha1String/getSha1ForString

---

<sup>**[vjudge-v2/UESTCJudger.cpp, line 21 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb6PmCTWSxWG0tEjsN)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/UESTCJudger.cpp#L21)):</sup>
"Custom"
Why do we need to customize this?

---

<sup>**[vjudge-v2/UESTCJudger.cpp, line 171 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb7EyYfILCrY7y43cr)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/UESTCJudger.cpp#L171)):</sup>
nit: no newline

---

<sup>**[vjudge-v2/UESTCJudger.h, line 2 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb7KkS0CdQd-CYIIzQ)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/UESTCJudger.h#L2)):</sup>
spaces

---

<sup>**[vjudge-v2/UESTCJudger.h, line 21 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb7MUz2Id3MYF2Fkxl)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/UESTCJudger.h#L21)):</sup>
spaces

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10)

**Comment by crccw** [comment]
---

<sup>**[vjudge-v2/GlobalHelpers.cpp, line 230 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb7aOoEZT5Mfb9w8ho)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/GlobalHelpers.cpp#L230)):</sup>
Done.

---

<sup>**[vjudge-v2/GlobalHelpers.cpp, line 232 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb7ZCg5rx-Yi7ghkaN)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/GlobalHelpers.cpp#L232)):</sup>
Done.

---

<sup>**[vjudge-v2/GlobalHelpers.cpp, line 235 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb7biOfbiexKnFZlVB)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/GlobalHelpers.cpp#L235)):</sup>
Done.

---

<sup>**[vjudge-v2/GlobalHelpers.cpp, line 351 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb6BEfWc6T8Rr8A1gB)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/GlobalHelpers.cpp#L351)):</sup>
Done.

---

<sup>**[vjudge-v2/GlobalHelpers.h, line 44 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb6G_kBIFhYR7o1Ag4)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/GlobalHelpers.h#L44)):</sup>
Done.

---

<sup>**[vjudge-v2/UESTCJudger.cpp, line 21 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb6PmCTWSxWG0tEjsN)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/UESTCJudger.cpp#L21)):</sup>
mentioned in the commit log
UESTC requires ContentType in header

---

<sup>**[vjudge-v2/UESTCJudger.h, line 2 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb7KkS0CdQd-CYIIzQ)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/UESTCJudger.h#L2)):</sup>
Done.

---

<sup>**[vjudge-v2/UESTCJudger.h, line 21 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb7MUz2Id3MYF2Fkxl)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/UESTCJudger.h#L21)):</sup>
Done.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10)

**Comment by crccw** [comment]
---

<sup>**[vjudge-v2/UESTCJudger.h, line 21 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb7MUz2Id3MYF2Fkxl)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/UESTCJudger.h#L21)):</sup>
huh...I find out that all header file has a strange white character after #endif

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10)

**Comment by crccw** [comment]
---

<sup>**[vjudge-v2/UESTCJudger.cpp, line 171 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-Jmb7EyYfILCrY7y43cr)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/4ffd70def1ebba9baf634875c2d7e783674510e3/vjudge-v2/UESTCJudger.cpp#L171)):</sup>
Done.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10)

**Comment by 51isoft** [comment]
Reviewed files:
- vjudge-v2/GlobalHelpers.cpp @ r2
- vjudge-v2/GlobalHelpers.h @ r2
- vjudge-v2/UESTCJudger.cpp @ r2

---

<sup>**[vjudge-v2/GlobalHelpers.h, line 50 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10#-JmenyE9XWyn9CIXc8xI)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/c55e42ddc291417f70deeafddd1be53eefdc5814/vjudge-v2/GlobalHelpers.h#L50)):</sup>
space

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10)

**Comment by 51isoft** [comment]
Reviewed files:
- vjudge-v2/UESTCJudger.h @ r2

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/10)

**Pull request merged**
