### PR TITLE
Cleanup legacy type confusions in Bott.cpp

### PR DESCRIPTION
**Pull request by crccw**
remote_runid is intented to be left as string, since it's entirely decided by remote judges.

[Review on Reviewable](https://reviewable.io/reviews/bnuacm/bnuoj-vjudge/17)

### CODE REVIEW

**Comment by 51isoft** [comment]
Review status: 0 of 28 files reviewed, 6 unresolved discussions, all commit checks successful.

---

<sup>**[vjudge-v2/HUSTJudger.cpp, line 51 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-JpoijlDlSyiZ0tikkA3)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9c9f6fb63b33c2d25e071411d40dce05f2056d8/vjudge-v2/HUSTJudger.cpp#L51)):</sup>
line too long

---

<sup>**[vjudge-v2/NBUTJudger.cpp, line 58 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-Jpoiq5S7T6DGen8TVJi)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9c9f6fb63b33c2d25e071411d40dce05f2056d8/vjudge-v2/NBUTJudger.cpp#L58)):</sup>
too long

---

<sup>**[vjudge-v2/NJUPTJudger.cpp, line 53 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-JpoirvhbVk2blUcqmB3)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9c9f6fb63b33c2d25e071411d40dce05f2056d8/vjudge-v2/NJUPTJudger.cpp#L53)):</sup>
too long

---

<sup>**[vjudge-v2/PKUJudger.cpp, line 55 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-Jpoiu5TwedITbAZuThs)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9c9f6fb63b33c2d25e071411d40dce05f2056d8/vjudge-v2/PKUJudger.cpp#L55)):</sup>
ditto

---

<sup>**[vjudge-v2/SCUJudger.cpp, line 62 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-JpoivgHh1t8TOQYu-O4)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9c9f6fb63b33c2d25e071411d40dce05f2056d8/vjudge-v2/SCUJudger.cpp#L62)):</sup>
ditto

---

<sup>**[vjudge-v2/UESTCJudger.cpp, line 55 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-Jpoj3Y-QuAeL76HOFUr)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9c9f6fb63b33c2d25e071411d40dce05f2056d8/vjudge-v2/UESTCJudger.cpp#L55)):</sup>
Worth using json library for uestc? Not in this PR though

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17)

**Comment by crccw** [comment]
Review status: 0 of 28 files reviewed, 6 unresolved discussions, all commit checks successful.

---

<sup>**[vjudge-v2/HUSTJudger.cpp, line 51 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-JpoijlDlSyiZ0tikkA3)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9c9f6fb63b33c2d25e071411d40dce05f2056d8/vjudge-v2/HUSTJudger.cpp#L51)):</sup>
Done.

---

<sup>**[vjudge-v2/NBUTJudger.cpp, line 58 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-Jpoiq5S7T6DGen8TVJi)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9c9f6fb63b33c2d25e071411d40dce05f2056d8/vjudge-v2/NBUTJudger.cpp#L58)):</sup>
Done.

---

<sup>**[vjudge-v2/NJUPTJudger.cpp, line 53 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-JpoirvhbVk2blUcqmB3)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9c9f6fb63b33c2d25e071411d40dce05f2056d8/vjudge-v2/NJUPTJudger.cpp#L53)):</sup>
Done.

---

<sup>**[vjudge-v2/PKUJudger.cpp, line 55 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-Jpoiu5TwedITbAZuThs)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9c9f6fb63b33c2d25e071411d40dce05f2056d8/vjudge-v2/PKUJudger.cpp#L55)):</sup>
Done.

---

<sup>**[vjudge-v2/SCUJudger.cpp, line 62 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-JpoivgHh1t8TOQYu-O4)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9c9f6fb63b33c2d25e071411d40dce05f2056d8/vjudge-v2/SCUJudger.cpp#L62)):</sup>
Done.

---

<sup>**[vjudge-v2/UESTCJudger.cpp, line 55 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-Jpoj3Y-QuAeL76HOFUr)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9c9f6fb63b33c2d25e071411d40dce05f2056d8/vjudge-v2/UESTCJudger.cpp#L55)):</sup>
Definitely I would like to use json library....

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17)

**Comment by 51isoft** [comment]
Review status: 0 of 28 files reviewed, 7 unresolved discussions, all commit checks successful.

---

<sup>**[vjudge-v2/Bott.cpp, line 3 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-JporvTbh_nlOFIny8g2)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/8ef90a07553f7ccaaec80679aec3668d5aeff5e5/vjudge-v2/Bott.cpp#L3)):</sup>
revert

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17)

**Comment by crccw** [comment]
Review status: 0 of 28 files reviewed, 7 unresolved discussions, all commit checks successful.

---

<sup>**[vjudge-v2/Bott.cpp, line 3 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17#-JporvTbh_nlOFIny8g2)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/8ef90a07553f7ccaaec80679aec3668d5aeff5e5/vjudge-v2/Bott.cpp#L3)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/17)

**Pull request merged**
