### PR TITLE
OpenJudge and PKU: try strip of comments when POST denied

### PR DESCRIPTION
**Pull request by crccw**
It works sometimes...

[Review on Reviewable](https://reviewable.io/reviews/bnuacm/bnuoj-vjudge/18)

### CODE REVIEW

**Comment by 51isoft** [comment]
Review status: 0 of 5 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[vjudge-v2/GlobalHelpers.cpp, line 384 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/18#-Jq8piqTK3HtTukRR3CR)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9ea750e36d7d25993359b6a97e31a15a1fbee96/vjudge-v2/GlobalHelpers.cpp#L384)):</sup>
I don't think I like this... I think we should find the root cause :(

---

<sup>**[vjudge-v2/VirtualJudger.cpp, line 58 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/18#-Jq8pXMjM92gCzXHDPSr)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9ea750e36d7d25993359b6a97e31a15a1fbee96/vjudge-v2/VirtualJudger.cpp#L58)):</sup>
Should this be handled by subclass? I don't think we should escape this in baseclass

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/18)

**Comment by crccw** [comment]
Review status: 0 of 5 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[vjudge-v2/GlobalHelpers.cpp, line 384 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/18#-Jq8piqTK3HtTukRR3CR)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9ea750e36d7d25993359b6a97e31a15a1fbee96/vjudge-v2/GlobalHelpers.cpp#L384)):</sup>
huh.. I'll try..

---

<sup>**[vjudge-v2/VirtualJudger.cpp, line 58 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/18#-Jq8pXMjM92gCzXHDPSr)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/a9ea750e36d7d25993359b6a97e31a15a1fbee96/vjudge-v2/VirtualJudger.cpp#L58)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/18)

**Comment by 51isoft** [comment]
What's the status of this?

**Comment by crccw** [comment]
Due to a recent update of OpenJudge, this is no longer needed. Now, source code are encoded in base64.

**Pull request closed without merging**
