### PR TITLE
fix NJUPT and update charset_convert

### PR DESCRIPTION
**Pull request by crccw**
[Review on Reviewable](https://reviewable.io/reviews/bnuacm/bnuoj-vjudge/14)

### CODE REVIEW

**Comment by 51isoft** [comment]
<sup>**[vjudge-v2/AizuJudger.cpp, line 171 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14#-JnoKOiuS74hG46nikHM)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/0b3cdacb958925ca592d06fd4cf04359ecb6cad6/vjudge-v2/AizuJudger.cpp#L171)):</sup>
So this is not buffer any more

---

<sup>**[vjudge-v2/GlobalHelpers.cpp, line 319 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14#-JnoKZg-ThmB-XSTpPQx)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/0b3cdacb958925ca592d06fd4cf04359ecb6cad6/vjudge-v2/GlobalHelpers.cpp#L319)):</sup>
Comment is wrong

---

<sup>**[vjudge-v2/GlobalHelpers.h, line 19 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14#-JnoKhL68Vv_XxM-5CNU)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/0b3cdacb958925ca592d06fd4cf04359ecb6cad6/vjudge-v2/GlobalHelpers.h#L19)):</sup>
remove

---

<sup>**[vjudge-v2/HDUJudger.cpp, line 190 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14#-JnoKkKb6vKNQ8xt_dwZ)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/0b3cdacb958925ca592d06fd4cf04359ecb6cad6/vjudge-v2/HDUJudger.cpp#L190)):</sup>
ditto

---

<sup>**[vjudge-v2/NJUPTJudger.cpp, line 187 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14#-JnoKmg17MtZzYyBSaij)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/0b3cdacb958925ca592d06fd4cf04359ecb6cad6/vjudge-v2/NJUPTJudger.cpp#L187)):</sup>
ditto

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14)

**Comment by crccw** [comment]
<sup>**[vjudge-v2/AizuJudger.cpp, line 171 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14#-JnoKOiuS74hG46nikHM)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/0b3cdacb958925ca592d06fd4cf04359ecb6cad6/vjudge-v2/AizuJudger.cpp#L171)):</sup>
my fault...

---

<sup>**[vjudge-v2/GlobalHelpers.cpp, line 319 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14#-JnoKZg-ThmB-XSTpPQx)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/0b3cdacb958925ca592d06fd4cf04359ecb6cad6/vjudge-v2/GlobalHelpers.cpp#L319)):</sup>
Done.

---

<sup>**[vjudge-v2/GlobalHelpers.h, line 19 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14#-JnoKhL68Vv_XxM-5CNU)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/0b3cdacb958925ca592d06fd4cf04359ecb6cad6/vjudge-v2/GlobalHelpers.h#L19)):</sup>
Done.

---

<sup>**[vjudge-v2/HDUJudger.cpp, line 190 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14#-JnoKkKb6vKNQ8xt_dwZ)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/0b3cdacb958925ca592d06fd4cf04359ecb6cad6/vjudge-v2/HDUJudger.cpp#L190)):</sup>
Done.

---

<sup>**[vjudge-v2/NJUPTJudger.cpp, line 187 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14#-JnoKmg17MtZzYyBSaij)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/0b3cdacb958925ca592d06fd4cf04359ecb6cad6/vjudge-v2/NJUPTJudger.cpp#L187)):</sup>
Done.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14)

**Comment by 51isoft** [comment]
<sup>**[vjudge-v2/GlobalHelpers.cpp, line 325 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14#-Jnrlm27fXvkbRoX6kpp)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/f223af2ec2ee5b42e26a8bebe257c024b79d0b6d/vjudge-v2/GlobalHelpers.cpp#L325)):</sup>
space-1

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14)

**Comment by crccw** [comment]
<sup>**[vjudge-v2/GlobalHelpers.cpp, line 325 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14#-Jnrlm27fXvkbRoX6kpp)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/f223af2ec2ee5b42e26a8bebe257c024b79d0b6d/vjudge-v2/GlobalHelpers.cpp#L325)):</sup>
Done.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/14)

**Pull request merged**
