### PR TITLE
Add CF Gym

### PR DESCRIPTION
**Pull request by crccw**
It's so similar to regular CF contests so I just modified the CF Vjudger :)

[Review on Reviewable](https://reviewable.io/reviews/bnuacm/bnuoj-vjudge/5)

### CODE REVIEW

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5)

---

<sup>**[vjudge-v2/CFJudger.cpp, line 118 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiiLIC9V0TjzcckhxOr)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/b30cd071d6165bbb7486999f0af030be9e0c86e6/vjudge-v2/CFJudger.cpp#L118)):</sup>
- contest +
  I don't think it's a good idea to use contest.length() to determine this. Can we make CFGymJudger as a subclass of this one?

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5)

---

<sup>**[vjudge-v2/CFJudger.cpp, line 118 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiiLIC9V0TjzcckhxOr)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/b30cd071d6165bbb7486999f0af030be9e0c86e6/vjudge-v2/CFJudger.cpp#L118)):</sup>
I have tried that, will have problems in constructor since it will send message through socket.. 

The way CF handling gyms is extremely similar to common contests, the only difference is that gyms have a separate url, so there's really no need creating another class and simply copying the code...

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5)

---

<sup>**[vjudge-v2/CFJudger.cpp, line 118 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiiLIC9V0TjzcckhxOr)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/b30cd071d6165bbb7486999f0af030be9e0c86e6/vjudge-v2/CFJudger.cpp#L118)):</sup>
You can modify the code move send socket part to a separate function called "sendInitialHandShakeMessage" or shorter version, make OJ string a protected variable that can be override.
You should probably add that function to virtualjudger base class and change every other one.
Then make diverged code in CFJudger to functions, and just override them.
After you done that, the subclass should be really small.

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5)

---

<sup>**[vjudge-v2/CFJudger.cpp, line 118 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiiLIC9V0TjzcckhxOr)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/b30cd071d6165bbb7486999f0af030be9e0c86e6/vjudge-v2/CFJudger.cpp#L118)):</sup>
Done.

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5)

---

<sup>**[vjudge-v2/CFGymJudger.cpp, line 26 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-Jio8OmjqVdfltejrZXW)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/7425b935ecc5a5a735bbfaca04ffaca95355f946/vjudge-v2/CFGymJudger.cpp#L26)):</sup>
Let's split the function so there's no need to copy the common part.

---

<sup>**[vjudge-v2/VirtualJudger.h, line 27 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-Jio7mn-WwAQgkBFRL41)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/7425b935ecc5a5a735bbfaca04ffaca95355f946/vjudge-v2/VirtualJudger.h#L27)):</sup>
Let's make it private and call this in VirtualJudger::run

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5)

---

<sup>**[vjudge-v2/CFGymJudger.cpp, line 26 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-Jio8OmjqVdfltejrZXW)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/7425b935ecc5a5a735bbfaca04ffaca95355f946/vjudge-v2/CFGymJudger.cpp#L26)):</sup>
Done.

---

<sup>**[vjudge-v2/VirtualJudger.h, line 27 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-Jio7mn-WwAQgkBFRL41)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/7425b935ecc5a5a735bbfaca04ffaca95355f946/vjudge-v2/VirtualJudger.h#L27)):</sup>
Done.

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5)

---

<sup>**[vjudge-v2/ACdreamJudger.h, line 18 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-Jiod9QyqEZjjNozIk0r)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/ACdreamJudger.h#L18)):</sup>
private

---

<sup>**[vjudge-v2/CFGymJudger.cpp, line 26 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiodMa3p6M1JgkihE_D)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/CFGymJudger.cpp#L26)):</sup>
So I believe this one can be removed.

---

<sup>**[vjudge-v2/CFJudger.cpp, line 291 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiodWu1f0q7I8z5QjjU)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/CFJudger.cpp#L291)):</sup>
getVerdictUrl

---

<sup>**[vjudge-v2/Logger.h, line 41 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiodkbqAfTAGe-QZz-E)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/Logger.h#L41)):</sup>
I believe this is a mistake

---

<sup>**[vjudge-v2/VirtualJudger.h, line 41 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-Jioe2mWZJ1kFEnFES5L)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/VirtualJudger.h#L41)):</sup>
Update docstring

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5)

---

<sup>**[vjudge-v2/ACdreamJudger.h, line 18 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-Jiod9QyqEZjjNozIk0r)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/ACdreamJudger.h#L18)):</sup>
Done.

---

<sup>**[vjudge-v2/CFGymJudger.cpp, line 26 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiodMa3p6M1JgkihE_D)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/CFGymJudger.cpp#L26)):</sup>
post field is different

---

<sup>**[vjudge-v2/CFJudger.cpp, line 291 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiodWu1f0q7I8z5QjjU)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/CFJudger.cpp#L291)):</sup>
Done.

---

<sup>**[vjudge-v2/Logger.h, line 41 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiodkbqAfTAGe-QZz-E)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/Logger.h#L41)):</sup>
Done.

---

<sup>**[vjudge-v2/VirtualJudger.h, line 41 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-Jioe2mWZJ1kFEnFES5L)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/VirtualJudger.h#L41)):</sup>
Done.

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5)

---

<sup>**[vjudge-v2/CFGymJudger.cpp, line 26 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiodMa3p6M1JgkihE_D)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/CFGymJudger.cpp#L26)):</sup>
Would it fail if I pass contest as part of the contest? I don't think it will.

Even if it fails, we can add a function like "processMoreParams"

---

<sup>**[vjudge-v2/CFGymJudger.cpp, line 33 [r6]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiohN5BxK885P3uqBZ4)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/3007c8487d3fbe8afd679caf9f8a2e60d92a94c1/vjudge-v2/CFGymJudger.cpp#L33)):</sup>
" + contest + "

---

<sup>**[vjudge-v2/VirtualJudger.h, line 41 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-Jioe2mWZJ1kFEnFES5L)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/VirtualJudger.h#L41)):</sup>
Just say "Send handshake message to dispatcher"

---

<sup>**[vjudge-v2/VirtualJudger.h, line 45 [r6]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiogIi7L0I605zl4Ei2)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/3007c8487d3fbe8afd679caf9f8a2e60d92a94c1/vjudge-v2/VirtualJudger.h#L45)):</sup>
remote (my fault, facepalm

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5)

---

<sup>**[vjudge-v2/CFGymJudger.cpp, line 26 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiodMa3p6M1JgkihE_D)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/CFGymJudger.cpp#L26)):</sup>
Done.

---

<sup>**[vjudge-v2/CFGymJudger.cpp, line 33 [r6]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiohN5BxK885P3uqBZ4)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/3007c8487d3fbe8afd679caf9f8a2e60d92a94c1/vjudge-v2/CFGymJudger.cpp#L33)):</sup>
Done.

---

<sup>**[vjudge-v2/VirtualJudger.h, line 41 [r5]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-Jioe2mWZJ1kFEnFES5L)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/86cacd796df5f525fdbab9a239f84196037544a2/vjudge-v2/VirtualJudger.h#L41)):</sup>
Done.

---

<sup>**[vjudge-v2/VirtualJudger.h, line 45 [r6]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiogIi7L0I605zl4Ei2)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/3007c8487d3fbe8afd679caf9f8a2e60d92a94c1/vjudge-v2/VirtualJudger.h#L45)):</sup>
Done.

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5)

---

<sup>**[vjudge-v2/CFJudger.cpp, line 168 [r7]](https://reviewable.io:443/reviews/bnuacm/bnuoj-vjudge/5#-JiombOV88ZYDbEiUJ_N)** ([raw file](https://github.com/bnuacm/bnuoj-vjudge/blob/24ecc0e7f330a54660e3717184e6c714aa6388e7/vjudge-v2/CFJudger.cpp#L168)):</sup>
No need (string)

---

**Pull request merged**
